In [9]:
"|IMPORT PACKAGES|"
import numpy              as np
import pandas             as pd
import datetime
from   bokeh.plotting     import show, figure, output_file, save
from   bokeh.io           import show, output_notebook, curdoc, export_png
from   bokeh.models       import ColumnDataSource,LinearAxis, Range1d, NumeralTickFormatter, LabelSet, Label, BoxAnnotation, DatetimeTickFormatter, Text, Span
from   bokeh.models.tools import HoverTool
from   bokeh.transform    import dodge
from   datetime           import datetime as dt

In [23]:
"|IMPORT DATA|"
path = r'https://github.com/ncachanosky/research/blob/master/Economic%20Series/'
file = r'Resumen%20Estadistico%20-%20Argentina.xlsx?raw=true'
IO   = path + file

sheet = 'MONTHLY'

data = pd.read_excel(IO, sheet_name = sheet, usecols="B,BZ,CD,CH,CI", skiprows=2, nrows=399, engine='openpyxl') # Be patient...

data = data.rename(columns={"Inflation IPC Nucleo 12M"          :"IPC_N"})
data = data.rename(columns={"Inflation IPC 12M"                 :"IPC"})
data = data.rename(columns={"Inflation IPC-C 12M"               :"IPC_C"})
data = data.rename(columns={"Inflacion Promedio por presidencia":"PROMEDIO"})

data["IPC_N"]    = data["IPC_N"]   *100
data["IPC"]      = data["IPC"]     *100
data["IPC_C"]    = data["IPC_C"]   *100
data["PROMEDIO"] = data["PROMEDIO"]*100
    
data = data.drop(data.index[0:12])

data.loc[184:239,"NK"]    = data.iloc[184,4] # Promedio Néstor Kirchner
data.loc[240:335,"CFK"]   = data.iloc[240,4] # Promedio Cristina Kirchner
data.loc[336:383,"MM"]    = data.iloc[336,4] # Promedio Macri
data.loc[384:398,"AF"]    = data.iloc[384,4] # Promedio Alberto Fernández
data.loc[  0:227,"IPC_C"] = np.nan

In [29]:
"|CHECK DATA|"
data

,MONTH,IPC_N,IPC,IPC_C,PROMEDIO,NK,CFK,MM,AF
212,2005-09-30,NaN,10.264594,10.264594,15.087323,15.087323,NaN,NaN,NaN
213,2005-10-31,NaN,10.688125,10.688125,15.087323,15.087323,NaN,NaN,NaN
214,2005-11-30,NaN,12.020960,12.020960,15.087323,15.087323,NaN,NaN,NaN
215,2005-12-31,NaN,12.328987,12.328987,15.087323,15.087323,NaN,NaN,NaN
216,2006-01-31,NaN,12.096522,12.096522,15.087323,15.087323,NaN,NaN,NaN
217,2006-02-28,NaN,11.486194,11.486194,15.087323,15.087323,NaN,NaN,NaN
218,2006-03-31,NaN,11.112471,11.112471,15.087323,15.087323,NaN,NaN,NaN
219,2006-04-30,NaN,11.645612,11.645612,15.087323,15.087323,NaN,NaN,NaN
220,2006-05-31,NaN,11.498302,11.498302,15.087323,15.087323,NaN,NaN,NaN
221,2006-06-30,NaN,11.021415,11.021415,15.087323,15.087323,NaN,NaN,NaN
222,2006-07-31,NaN,10.595940,10.595940,15.087323,15.087323,NaN,NaN,NaN
223,2006-08-31,NaN,10.734301,10.734301,15.087323,15.087323,NaN,NaN,NaN
224,2006-09-30,NaN,10.445721,10.445721,15.087323,15.087323,NaN,NaN,NaN
225,2006-10-31,NaN,10.527364,10.527364,15.087323,15.087323,NaN,NaN,NaN
226,2006-11-30,NaN,9.982697,9.982697,15.087323,15.087323,NaN,NaN,NaN
227,2006-12-31,NaN,9.839028,9.839028,15.087323,15.087323,NaN,NaN,NaN
228,2007-01-31,NaN,9.696345,10.082134,15.087323,15.087323,NaN,NaN,NaN
229,2007-02-28,NaN,9.593123,10.634401,15.087323,15.087323,NaN,NaN,NaN
230,2007-03-31,NaN,9.117782,10.847170,15.087323,15.087323,NaN,NaN,NaN
231,2007-04-30,NaN,8.871080,12.414257,15.087323,15.087323,NaN,NaN,NaN
232,2007-05-31,NaN,8.816303,14.128425,15.087323,15.087323,NaN,NaN,NaN
233,2007-06-30,NaN,8.770411,16.417907,15.087323,15.087323,NaN,NaN,NaN
234,2007-07-31,NaN,8.639932,18.133705,15.087323,15.087323,NaN,NaN,NaN
235,2007-08-31,NaN,8.666472,21.114560,15.087323,15.087323,NaN,NaN,NaN
236,2007-09-30,NaN,8.561039,22.075611,15.087323,15.087323,NaN,NaN,NaN
237,2007-10-31,NaN,8.374663,22.976257,15.087323,15.087323,NaN,NaN,NaN
238,2007-11-30,NaN,8.531356,24.432248,15.087323,15.087323,NaN,NaN,NaN
239,2007-12-31,NaN,8.473696,25.687643,15.087323,15.087323,NaN,NaN,NaN
240,2008-01-31,NaN,8.244868,26.430624,25.557061,NaN,25.557061,NaN,NaN
241,2008-02-29,NaN,8.422933,26.931836,25.557061,NaN,25.557061,NaN,NaN
242,2008-03-31,NaN,8.815743,29.185063,25.557061,NaN,25.557061,NaN,NaN
243,2008-04-30,NaN,8.908972,28.932749,25.557061,NaN,25.557061,NaN,NaN
244,2008-05-31,NaN,9.063578,28.427130,25.557061,NaN,25.557061,NaN,NaN
245,2008-06-30,NaN,9.274866,27.925951,25.557061,NaN,25.557061,NaN,NaN
246,2008-07-31,NaN,9.132676,27.925951,25.557061,NaN,25.557061,NaN,NaN
247,2008-08-31,NaN,9.008445,26.561077,25.557061,NaN,25.557061,NaN,NaN
248,2008-09-30,NaN,8.692773,26.187740,25.557061,NaN,25.557061,NaN,NaN
249,2008-10-31,NaN,8.418797,25.566738,25.557061,NaN,25.557061,NaN,NaN
250,2008-11-30,NaN,7.866782,24.088032,25.557061,NaN,25.557061,NaN,NaN
251,2008-12-31,NaN,7.237358,22.993138,25.557061,NaN,25.557061,NaN,NaN
252,2009-01-31,NaN,6.811732,22.270357,25.557061,NaN,25.557061,NaN,NaN
253,2009-02-28,NaN,6.774267,21.787552,25.557061,NaN,25.557061,NaN,NaN
254,2009-03-31,NaN,6.255224,19.427328,25.557061,NaN,25.557061,NaN,NaN
255,2009-04-30,NaN,5.730000,18.258764,25.557061,NaN,25.557061,NaN,NaN
256,2009-05-31,NaN,5.489260,17.211196,25.557061,NaN,25.557061,NaN,NaN
257,2009-06-30,NaN,5.266798,15.489190,25.557061,NaN,25.557061,NaN,NaN
258,2009-07-31,NaN,5.533130,14.471166,25.557061,NaN,25.557061,NaN,NaN
259,2009-08-31,NaN,5.908868,13.685579,25.557061,NaN,25.557061,NaN,NaN
260,2009-09-30,NaN,6.151896,13.461347,25.557061,NaN,25.557061,NaN,NaN
261,2009-10-31,NaN,6.543054,13.349121,25.557061,NaN,25.557061,NaN,NaN

In [25]:
"|BUILD PLOT|"

cds = ColumnDataSource(data)

labels = ["Inflación Núcleo" ,
          "Inflación Oficial",
          "Inflación Congreso"]

text1 = Label(x=25, y=300, x_units='screen', y_units='screen', text_font_size="12px", text_color="darkslategrey",
              text="INFLACIÓN PROMEDIO ANUAL")

text2 = Label(x=25, y=285, x_units='screen', y_units='screen', text_font_size="12px", text_color="darkslategrey",
              text="Néstor Kirchner = 15.3%")

text3 = Label(x=25, y=270, x_units='screen', y_units='screen', text_font_size="12px", text_color="darkslategrey",
              text="Crsinta F. de Kirchner = 25.6%")

text4 = Label(x=25, y=255, x_units='screen', y_units='screen', text_font_size="12px", text_color="darkslategrey",
              text="Kirchnerismo = 20.4%")

text5 = Label(x=25, y=240, x_units='screen', y_units='screen', text_font_size="12px", text_color="darkslategrey",
              text="Mauricio Macri = 42.1%")

text6 = Label(x=25, y=225, x_units='screen', y_units='screen', text_font_size="12px", text_color="darkslategrey",
              text="Alberto Fernández = 38.8%")


#BCRA Presidents shades and names
PratGay     = BoxAnnotation(left=dt(2002,12,31).timestamp()*1000, right=dt(2004, 9,23).timestamp()*1000, line_color="black", fill_color="skyblue", fill_alpha=0.1)
Redrado     = BoxAnnotation(left=dt(2004, 9,24).timestamp()*1000, right=dt(2010, 1,10).timestamp()*1000, line_color="black", fill_color="purple" , fill_alpha=0.1)
delPont     = BoxAnnotation(left=dt(2010, 1,23).timestamp()*1000, right=dt(2013,11,18).timestamp()*1000, line_color="black", fill_color="green"  , fill_alpha=0.1)
Fabrega     = BoxAnnotation(left=dt(2013,11,19).timestamp()*1000, right=dt(2014,10, 1).timestamp()*1000, line_color="black", fill_color="orange" , fill_alpha=0.1)
Vanoli      = BoxAnnotation(left=dt(2014,10, 2).timestamp()*1000, right=dt(2015,12,10).timestamp()*1000, line_color="black", fill_color="black"  , fill_alpha=0.1)
Sturz       = BoxAnnotation(left=dt(2015,12,11).timestamp()*1000, right=dt(2018, 6,14).timestamp()*1000, line_color="black", fill_color="gold"   , fill_alpha=0.1)
Caputo      = BoxAnnotation(left=dt(2018, 6,15).timestamp()*1000, right=dt(2018, 9,25).timestamp()*1000, line_color="black", fill_color="gray"   , fill_alpha=0.1)
Sandleris   = BoxAnnotation(left=dt(2018, 9,26).timestamp()*1000, right=dt(2019,12,10).timestamp()*1000, line_color="black", fill_color="maroon" , fill_alpha=0.1)

PratGay_N   = Label(x=dt(2003,11, 2).timestamp()*1000, y=65, text="Prat-Gay"      , text_font_size="8pt", text_align="center", angle_units="deg", angle= 0)
Redrado_N   = Label(x=dt(2007, 5,25).timestamp()*1000, y=65, text="Redrado"       , text_font_size="8pt", text_align="center", angle_units="deg", angle= 0)
delPont_N   = Label(x=dt(2011,12,11).timestamp()*1000, y=65, text="Marcó del Pont", text_font_size="8pt", text_align="center", angle_units="deg", angle= 0)
Fabrega_N   = Label(x=dt(2014, 6,26).timestamp()*1000, y=67, text="Fábrega"       , text_font_size="8pt", text_align="right" , angle_units="deg", angle=90)
Vanoli_N    = Label(x=dt(2015, 7, 7).timestamp()*1000, y=67, text="Vanoli"        , text_font_size="8pt", text_align="right" , angle_units="deg", angle=90)
Sturz_N     = Label(x=dt(2017, 5,12).timestamp()*1000, y=67, text="Sturzenneger"  , text_font_size="8pt", text_align="right" , angle_units="deg", angle=90)
Caputo_N    = Label(x=dt(2018,10, 4).timestamp()*1000, y=67, text="Caputo"        , text_font_size="8pt", text_align="right" , angle_units="deg", angle=90)
Sandleris_N = Label(x=dt(2019, 7, 3).timestamp()*1000, y=67, text="Sandleris"     , text_font_size="8pt", text_align="right" , angle_units="deg", angle=90)


#BUILD FIGURE
p = figure(title = "EL HUB ECONÓMICO | INFLACIÓN INTERANUAL",
           y_range      = (-10, 70),
           x_range      = (dt(1999, 1,31).timestamp()*1000, dt(2021, 3,31).timestamp()*1000),
           plot_height  = 400,
           plot_width   = 700)

p.xaxis[0].formatter = DatetimeTickFormatter(months="%b %Y")
p.toolbar_location = "right"
p.toolbar.autohide = True

#AXIS 1 (LEFT)
#Inflación interanual
p1 = p.line("MONTH", "IPC_N", color="green", line_alpha=0.75, width=2, legend_label=labels[0], source=cds, muted_alpha=0.20)
p2 = p.line("MONTH", "IPC"  , color="black", line_alpha=0.75, width=2, legend_label=labels[1], source=cds, muted_alpha=0.20)
p3 = p.line("MONTH", "IPC_C", color="blue" , line_alpha=0.75, width=2, legend_label=labels[2], source=cds, muted_alpha=0.20)

#Inflación promedio
p4 = p.line("MONTH", "NK" , color="red", line_alpha=0.75, width=2, line_dash=[4,4], source=cds)
p5 = p.line("MONTH", "CFK", color="red", line_alpha=0.75, width=2, line_dash=[4,4], source=cds)
p6 = p.line("MONTH", "MM" , color="red", line_alpha=0.75, width=2, line_dash=[4,4], source=cds)
p7 = p.line("MONTH", "AF" , color="red", line_alpha=0.75, width=2, line_dash=[4,4], source=cds)

p.add_tools(HoverTool(renderers=[p1], tooltips = [("Inflación Núcleo"  , "@IPC_N{0.0}")], mode="vline"))
p.add_tools(HoverTool(renderers=[p2], tooltips = [("Inflación Oficial" , "@IPC{0.0}")]  , mode="vline"))
p.add_tools(HoverTool(renderers=[p3], tooltips = [("Inflación Congreso", "@IPC_C{0.0}")], mode="vline"))

p.add_layout(text1)
p.add_layout(text2)
p.add_layout(text3)
p.add_layout(text4)
p.add_layout(text5)
p.add_layout(text6)

#ADD BCRA PRESIDENTS
p.add_layout(PratGay)
p.add_layout(Redrado)
p.add_layout(delPont)
p.add_layout(Fabrega)
p.add_layout(Vanoli)
p.add_layout(Sturz)
p.add_layout(Caputo)
p.add_layout(Sandleris)

p.add_layout(PratGay_N)
p.add_layout(Redrado_N)
p.add_layout(delPont_N)
p.add_layout(Fabrega_N)
p.add_layout(Vanoli_N)
p.add_layout(Sturz_N)
p.add_layout(Caputo_N)
p.add_layout(Sandleris_N)

#LEGEND
p.xaxis[0].formatter = DatetimeTickFormatter(months="%m %Y")
h_axis = Span(location=0, dimension="width", line_color="black")
p.add_layout(h_axis)
p.legend.location     = "bottom_right"
p.legend.orientation  = "horizontal"
p.legend.click_policy = "mute"
show(p)

In [ ]:
"|EXPORT .PNG FILE|"

export_png(p, filename="inflacion_interanual.png")

In [ ]:
"|# CREATE HTML FILE|"

output_file(filename="inflacion_interanual.html", title="Deuda pública")
save(p)

In [5]:
"|CREATE JSON FILE|"
import json
import bokeh.embed

from bokeh.embed import json_item

j = json.dumps(json_item(p, "inflacion_interanual"))
with open("inflacion_interanual.json", "w") as fp:
    json.dump(j, fp)