In [138]:
"|IMPORT PACKAGES|"
import pandas             as pd
import numpy              as np
import statsmodels.api    as sm
import datetime
from   bokeh.plotting     import show, figure, output_file, save
from   bokeh.io           import show, output_notebook, curdoc, export_png
from   bokeh.models       import ColumnDataSource,LinearAxis, Range1d, NumeralTickFormatter, LabelSet, Label
from   bokeh.models       import BoxAnnotation, DatetimeTickFormatter, Span
from   bokeh.models.tools import HoverTool
from   bokeh.transform    import dodge

In [172]:
"|IMPORT DATA|"
path = r'https://github.com/ncachanosky/research/blob/master/Economic%20Series/'
file = r'Resumen%20Estadistico%20-%20Internacional.xlsx?raw=true'

IO   = path + file

sheet = 'DATA'

data = pd.read_excel(IO, sheet_name = sheet, usecols="A:G,M", skiprows=2, engine='openpyxl') # Be patient...

data = data.rename(columns={"GDP (PPP)":"TREND"})
data = data[data.REGION == 'Latin America']
data = data[data.YEAR > 1999]
data = data[data.YEAR < 2020].reset_index()
data = data.drop(['index'], axis = 1)

In [173]:
data

,YEAR,ISO CODE,COUNTRY,REGION,EFW,QUART,EFW_A1,TREND
0,2000,AIA,Anguilla,Latin America,NaN,NaN,NaN,NaN
1,2000,ATG,Antigua and Barbuda,Latin America,NaN,NaN,NaN,18311.013715
2,2000,ARG,Argentina,Latin America,7.25,2.0,8.001421,18625.288101
3,2000,ABW,Aruba,Latin America,NaN,NaN,NaN,41022.321554
4,2000,BHS,Bahamas,Latin America,7.24,2.0,8.535943,40517.363844
...,...,...,...,...,...,...,...,...
1035,2019,TTO,Trinidad and Tobago,Latin America,NaN,NaN,NaN,26175.836979
1036,2019,TCA,Turks and Caicos Islands,Latin America,NaN,NaN,NaN,29253.376603
1037,2019,VIR,United States Virgin Islands,Latin America,NaN,NaN,NaN,NaN
1038,2019,URY,Uruguay,Latin America,NaN,NaN,NaN,21561.062055
1039,2019,VEN,Venezuela,Latin America,NaN,NaN,NaN,NaN

In [174]:
y_ARG = data[data.COUNTRY == 'Argentina'].reset_index().drop(['index'], axis = 1)
y_BRA = data[data.COUNTRY == 'Brazil'].reset_index().drop(['index'], axis = 1)
y_CHI = data[data.COUNTRY == 'Chile'].reset_index().drop(['index'], axis = 1)
y_COL = data[data.COUNTRY == 'Colombia'].reset_index().drop(['index'], axis = 1)
y_ECU = data[data.COUNTRY == 'Ecuador'].reset_index().drop(['index'], axis = 1)
y_MEX = data[data.COUNTRY == 'Mexico'].reset_index().drop(['index'], axis = 1)
y_PAN = data[data.COUNTRY == 'Panama'].reset_index().drop(['index'], axis = 1)
y_PAR = data[data.COUNTRY == 'Paraguay'].reset_index().drop(['index'], axis = 1)
y_PER = data[data.COUNTRY == 'Peru'].reset_index().drop(['index'], axis = 1)

In [175]:
y_ARG['CYCLE'], y_ARG['TREND'] = sm.tsa.filters.hpfilter(y_ARG['TREND'], 6.25)
y_BRA['CYCLE'], y_BRA['TREND'] = sm.tsa.filters.hpfilter(y_BRA['TREND'], 6.25)
y_CHI['CYCLE'], y_CHI['TREND'] = sm.tsa.filters.hpfilter(y_CHI['TREND'], 6.25)
y_COL['CYCLE'], y_COL['TREND'] = sm.tsa.filters.hpfilter(y_COL['TREND'], 6.25)
y_ECU['CYCLE'], y_ECU['TREND'] = sm.tsa.filters.hpfilter(y_ECU['TREND'], 6.25)
y_MEX['CYCLE'], y_MEX['TREND'] = sm.tsa.filters.hpfilter(y_MEX['TREND'], 6.25)
y_PAN['CYCLE'], y_PAN['TREND'] = sm.tsa.filters.hpfilter(y_PAN['TREND'], 6.25)
y_PAR['CYCLE'], y_PAR['TREND'] = sm.tsa.filters.hpfilter(y_PAR['TREND'], 6.25)
y_PER['CYCLE'], y_PER['TREND'] = sm.tsa.filters.hpfilter(y_PER['TREND'], 6.25)

y_ARG['TREND'] = y_ARG['TREND']/y_ARG['TREND'][0] * 100
y_BRA['TREND'] = y_BRA['TREND']/y_BRA['TREND'][0] * 100
y_CHI['TREND'] = y_CHI['TREND']/y_CHI['TREND'][0] * 100
y_COL['TREND'] = y_COL['TREND']/y_COL['TREND'][0] * 100
y_ECU['TREND'] = y_ECU['TREND']/y_ECU['TREND'][0] * 100
y_MEX['TREND'] = y_MEX['TREND']/y_MEX['TREND'][0] * 100
y_PAN['TREND'] = y_PAN['TREND']/y_PAN['TREND'][0] * 100
y_PAR['TREND'] = y_PAR['TREND']/y_PAR['TREND'][0] * 100
y_PER['TREND'] = y_PER['TREND']/y_PER['TREND'][0] * 100

In [179]:
"|BUILD PLOT|"

Y = ['Argentina',  # 5.95
     'Brasil'   ,  # 6.40
     'Chile'    ,  # 7.86
     'Colombia' ,  # 6.56
     'Ecuador'  ,  # 6.18
     'Mexico'   ,  # 6.86
     'Panamá'   ,  # 7.64
     'Paraguay' ,  # 7.01
     'Peru']       # 7.71

x_ARG = (y_ARG['TREND'][19]/y_ARG['TREND'][0] - 1)
x_BRA = (y_BRA['TREND'][19]/y_BRA['TREND'][0] - 1)
x_CHI = (y_CHI['TREND'][19]/y_CHI['TREND'][0] - 1)
x_COL = (y_COL['TREND'][19]/y_COL['TREND'][0] - 1)
x_ECU = (y_ECU['TREND'][19]/y_ECU['TREND'][0] - 1)
x_MEX = (y_MEX['TREND'][19]/y_MEX['TREND'][0] - 1)
x_PAN = (y_PAN['TREND'][19]/y_PAN['TREND'][0] - 1)
x_PAR = (y_PAR['TREND'][19]/y_PAN['TREND'][0] - 1)
x_PER = (y_PER['TREND'][19]/y_PER['TREND'][0] - 1)

X = [x_ARG,
     x_BRA,
     x_CHI,
     x_COL,
     x_ECU,
     x_MEX,
     x_PAN,
     x_PAR,
     x_PER]

#BUILD FIGURE
p = figure(title        = "EL HUB ECONÓMICO | CRECIMIENTO EN LATINO AMÉRICA: TENDENCIA (PAÍSES SELECTOS)",
           x_axis_label = "",
           y_axis_label = "",
           y_range      = Y,
           plot_height  = 400,
           plot_width   = 700)

p.toolbar_location = "right"
p.toolbar.autohide = True

#AXIS 1 (LEFT)
p.hbar(y          = Y          , 
       left       = 0          ,
       right      = X          ,
       height     = 0.5        ,
       color      = "steelblue",
       fill_alpha = 0.75)

#LEGEND
p.xaxis.ticker = np.arange(0,1.4,0.2)
show(p)

In [ ]:
"|EXPORT .PNG FILE|"

export_png(p, filename="crecimiento_desde_2020.png")

In [ ]:
"|# CREATE HTML FILE|"

output_file(filename="crecimiento_desde_2020.html", title="Crecimiento tendencia")
save(p)

In [171]:
y_ARG

,YEAR,ISO CODE,COUNTRY,REGION,EFW,QUART,EFW_A1,GDP (PPP)
0,2000,ARG,Argentina,Latin America,7.250000,2.0,8.001421,18625.288101
1,2001,ARG,Argentina,Latin America,6.835657,2.0,8.019804,17610.751608
2,2002,ARG,Argentina,Latin America,6.328606,3.0,7.789725,15523.036305
3,2003,ARG,Argentina,Latin America,6.236975,3.0,7.950486,16714.669256
4,2004,ARG,Argentina,Latin America,6.341765,3.0,7.993141,18032.610491
5,2005,ARG,Argentina,Latin America,6.083443,3.0,7.436811,19426.436648
6,2006,ARG,Argentina,Latin America,6.127138,4.0,7.236361,20777.651654
7,2007,ARG,Argentina,Latin America,6.309387,3.0,7.074693,22424.122250
8,2008,ARG,Argentina,Latin America,6.224208,3.0,6.885549,23103.455946
9,2009,ARG,Argentina,Latin America,6.017405,4.0,6.298287,21519.892554
10,2010,ARG,Argentina,Latin America,5.817749,4.0,6.469553,23521.270176
11,2011,ARG,Argentina,Latin America,5.848895,4.0,6.229325,24647.629275
12,2012,ARG,Argentina,Latin America,5.330657,4.0,6.107741,24118.867517
13,2013,ARG,Argentina,Latin America,5.135726,4.0,5.924674,24424.136448
14,2014,ARG,Argentina,Latin America,4.688323,4.0,5.681079,23550.099061
15,2015,ARG,Argentina,Latin America,5.173626,4.0,6.014723,23933.886613
16,2016,ARG,Argentina,Latin America,5.546110,4.0,5.933256,23189.527446
17,2017,ARG,Argentina,Latin America,5.975281,4.0,6.064430,23597.117753
18,2018,ARG,Argentina,Latin America,5.782274,4.0,6.048118,22759.398560
19,2019,ARG,Argentina,Latin America,NaN,NaN,NaN,22063.904372

In [180]:
"|CREATE JSON FILE|"
import json
import bokeh.embed

from bokeh.embed import json_item

j = json.dumps(json_item(p, "crecimiento_desde_2020"))
with open("crecimiento_desde_2020.json", "w") as fp:
    json.dump(j, fp)