In [1]:
"|IMPORT PACKAGES|"
import pandas             as pd
import datetime
from   bokeh.plotting     import show, figure, output_file, save
from   bokeh.io           import show, output_notebook, curdoc, export_png
from   bokeh.models       import ColumnDataSource,LinearAxis, Range1d, NumeralTickFormatter, LabelSet, Label, BoxAnnotation, DatetimeTickFormatter
from   bokeh.models.tools import HoverTool
from   bokeh.transform    import dodge

In [11]:
"|IMPORT DATA|"
path = r'https://github.com/ncachanosky/research/blob/master/Economic%20Series/'
file = r'Resumen%20Estadistico%20-%20Internacional.xlsx?raw=true'

IO   = path + file

sheet = 'DATA'

data = pd.read_excel(IO, sheet_name = sheet, usecols="A:F,L,Q", skiprows=2, engine='openpyxl') # Be patient...

data = data.rename(columns={"GDP (PPP)":"GDP"})
data = data.rename(columns={"GINI (WB)":"GINI"})
data = data[data.YEAR == 2018].reset_index()
data = data.drop(['index'], axis = 1)

In [12]:
"|CHECK DATA|"
data

,YEAR,ISO CODE,COUNTRY,REGION,EFW,QUART,POPULATION,GINI
0,2018,DZA,Algeria,Africa,4.967744,4.0,42228429.0,NaN
1,2018,AGO,Angola,Africa,4.749723,4.0,30809762.0,51.3
2,2018,BEN,Benin,Africa,6.199911,4.0,11485048.0,NaN
3,2018,BWA,Botswana,Africa,7.603481,2.0,2254126.0,NaN
4,2018,IOT,British Indian Ocean Territory,Africa,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...
243,2018,TON,Tonga,Oceania,NaN,NaN,103197.0,NaN
244,2018,TUV,Tuvalu,Oceania,NaN,NaN,11508.0,NaN
245,2018,UMI,United States Minor Outlying Islands,Oceania,NaN,NaN,NaN,NaN
246,2018,VUT,Vanuatu,Oceania,NaN,NaN,292680.0,NaN
247,2018,WLF,Wallis and Futuna Islands,Oceania,NaN,NaN,NaN,NaN

In [13]:
"|BUILD PLOT|"

X = ['Menor libertad económica',
     '3er cuartil'             ,
     '2do cuartil'             ,
     'Mayor libertad económica']

Q1 = data[data.QUART == 1]
Q2 = data[data.QUART == 2]
Q3 = data[data.QUART == 3]
Q4 = data[data.QUART == 4]

BAR1 = Q1['GINI'].mean()
BAR2 = Q2['GINI'].mean()
BAR3 = Q3['GINI'].mean()
BAR4 = Q4['GINI'].mean()

BAR = [BAR1, BAR2, BAR3, BAR4]

colors = ['red', 'gold', 'green', 'blue']

#BUILD FIGURE
p = figure(title        = "EL HUB ECONÓMICO | LIBERTAD ECONÓMICA E ÍNDICE DE GINI",
           x_axis_label = "",
           y_axis_label = "% del ingreso total",
           y_range      = (0, 60),
           x_range      = X,
           plot_height  = 400,
           plot_width   = 700)

p.toolbar_location = "right"
p.toolbar.autohide = True

#AXIS 1 (LEFT)
p.vbar(x=X            ,
       top=BAR        ,
       color=colors   ,
       width=0.5      ,
       fill_alpha=0.5)

#LEGEND
show(p)

In [ ]:
"|EXPORT .PNG FILE|"

export_png(p, filename="efw_GINI.png")

In [ ]:
"|# CREATE HTML FILE|"

output_file(filename="efw_GINI.html", title="EFW y GINI")
save(p)

In [14]:
"|CREATE JSON FILE|"
import json
import bokeh.embed

from bokeh.embed import json_item

j = json.dumps(json_item(p, "efw_GINI"))
with open("efw_GINI.json", "w") as fp:
    json.dump(j, fp)

In [10]:
Q2

Empty DataFrame
Columns: [level_0, index, YEAR, ISO CODE, COUNTRY, REGION, EFW, QUART, POPULATION, GINI]
Index: []