In [1]:
"|IMPORT PACKAGES|"
import numpy              as np
import pandas             as pd
import datetime
from   bokeh.plotting     import show, figure, output_file, save
from   bokeh.io           import show, output_notebook, curdoc, export_png
from   bokeh.models       import ColumnDataSource,LinearAxis, Range1d, NumeralTickFormatter, LabelSet, Label, BoxAnnotation, DatetimeTickFormatter, Text, Span
from   bokeh.models.tools import HoverTool
from   bokeh.models       import Arrow, NormalHead, OpenHead, VeeHead
from   bokeh.transform    import dodge
from   datetime           import datetime as dt

In [2]:
"|IMPORT DATA|"
path = r'https://github.com/ncachanosky/research/blob/master/Economic%20Series/'
file = r'Resumen%20Estadistico%20-%20Argentina.xlsx?raw=true'
IO   = path + file

sheet = 'BCRA'

data = pd.read_excel(IO, sheet_name = sheet, usecols="A, M, O, AN", skiprows=1, nrows=1112, engine='openpyxl') # Be patient...

data = data.rename(columns={"Fechas"            :"WEEK"})
data = data.rename(columns={"Lebacs [ARS]"      :"LEBACS"})
data = data.rename(columns={"Leliqs"            :"LELIQS"})
data = data.rename(columns={"(LEBACS+LELIQS)/BM":"LL_BM"})

data['LL_BM']  = data['LL_BM'] *100
data['LEBACS'] = data['LEBACS']/1000000
data['LELIQS'] = data['LELIQS']/1000000

In [12]:
"|CHECK DATA|"
data

           WEEK    LEBACS       LELIQS       LL_BM
0    1998-01-07       NaN          NaN    0.000000
1    1998-01-15       NaN          NaN    0.000000
2    1998-01-23       NaN          NaN    0.000000
3    1998-01-31       NaN          NaN    0.000000
4    1998-02-07       NaN          NaN    0.000000
...         ...       ...          ...         ...
1107 2021-01-31  0.000000  2917.448695  117.576957
1108 2021-02-07  0.000000  2737.712637  105.851154
1109 2021-02-15  1.531669  2894.103304  115.121799
1110 2021-02-23  1.976552  2937.911450  114.998612
1111 2021-02-28  2.855839  3102.782907  128.924251

[1112 rows x 4 columns]

In [6]:
"|BUILD PLOT|"

cds = ColumnDataSource(data)

#BUILD FIGURE
p = figure(title = "EL HUB ECONÓMICO | PASIVOS REMUNERADOS DEL BCRA",
           y_range      = (0, 3500),
           x_axis_label = "",
           y_axis_label = "Millones de pesos",
           x_range      = (dt(2015, 1,31).timestamp()*1000, dt(2021, 2,28).timestamp()*1000),
           x_axis_type  = "datetime",
           plot_height  = 400,
           plot_width   = 700)

p.toolbar_location = "right"
p.toolbar.autohide = True

#AXIS 1 (LEFT)
p.varea(y1=0, y2='LEBACS', x='WEEK', legend_label='Lebacs y Nobacs', fill_color='blue', alpha=0.5, muted_alpha=0.2, source=cds)
p.varea(y1=0, y2='LELIQS', x='WEEK', legend_label='Leliqs'         , fill_color='gray', alpha=0.5, muted_alpha=0.2, source=cds) 

p1 = p.line('WEEK', 'LEBACS', color='blue', line_alpha=0.75, width=2, source=cds)
p2 = p.line('WEEK', 'LELIQS', color='gray', line_alpha=0.75, width=2, source=cds)

p.add_tools(HoverTool(renderers=[p1], tooltips = [("Lebacs y Nobacs"  , "@LEBACS{$0,0}")], mode="vline"))
p.add_tools(HoverTool(renderers=[p2], tooltips = [("Leliqs"           , "@LELIQS{$0,0}")], mode="vline"))

#AXIS 2 (RIGHT)
p.extra_y_ranges = {'y2': Range1d(start=1, end=160)}
p.add_layout(LinearAxis(y_range_name='y2', axis_label='Pasivos remunerados/BM'), 'right')

p3 = p.line('WEEK', 'LL_BM', y_range_name='y2', color='red', legend_label='Pasivos/BM', line_width=2, line_alpha=0.75, muted_alpha=0.2, source=cds)
p.add_tools(HoverTool(renderers=[p3], tooltips = [("Pasivos/BM", "@LL_BM{0.0}")], mode="vline"))

#LEGEND
#h_axis = Span(location=0, dimension="width", line_color="black")
#p.add_layout(h_axis)
p.xaxis[0].formatter = DatetimeTickFormatter(months='%b %Y')
p.yaxis[0].formatter = NumeralTickFormatter(format="$0,0")
p.legend.location     = "top_left"
p.legend.orientation  = "vertical"
p.legend.click_policy = "mute"
show(p)

In [ ]:
"|EXPORT .PNG FILE|"

export_png(p, filename="pasivos_bcra.png")

In [ ]:
"|# CREATE HTML FILE|"

output_file(filename="pasivos_bcra.html", title="Pasivos del BCRA")
save(p)

In [7]:
"|CREATE JSON FILE|"
import json
import bokeh.embed

from bokeh.embed import json_item

j = json.dumps(json_item(p, "pasivos_bcra"))
with open("pasivos_bcra.json", "w") as fp:
    json.dump(j, fp)