In [1]:
"|IMPORT PACKAGES|"
import pandas             as pd
from   bokeh.plotting     import show, figure, output_file, save
from   bokeh.io           import show, output_notebook, curdoc, export_png
from   bokeh.models       import LinearAxis, Range1d, ColumnDataSource, Label
from   bokeh.models.tools import HoverTool
from   bokeh.transform    import dodge

In [2]:
"|IMPORT DATA|"
path = r'https://github.com/ncachanosky/research/blob/master/Economic%20Series/'
file = r'Resumen%20Estadistico%20-%20Argentina.xlsx?raw=true'

IO   = path + file

sheet = 'PBI'

data = pd.read_excel(IO, sheet_name = sheet, usecols="A:F", skiprows=10, nrows=28, engine='openpyxl') # Be patient...
data = data.rename(columns={"%PBI (1993)":"1993"})
data = data.rename(columns={"%PBI (2004)":"2004"})
data = data.rename(columns={"2015 = 100":"Y_100"})

In [3]:
"|CHECK DATA|"
data

    YEAR     PBI (1993)     PBI (2004)       1993       2004       Y_100
0   1993  236504.980232            NaN        NaN        NaN         NaN
1   1994  250307.885536            NaN   5.836201        NaN   60.292978
2   1995  243186.101519            NaN  -2.845210        NaN   58.577516
3   1996  256626.243056            NaN   5.526690        NaN   61.814914
4   1997  277441.317622            NaN   8.111047        NaN   66.828750
5   1998  288123.304608            NaN   3.850179        NaN   69.401777
6   1999  278369.013872            NaN  -3.385457        NaN   67.052209
7   2000  276172.685353            NaN  -0.788999        NaN   66.523168
8   2001  263996.674367            NaN  -4.408840        NaN   63.590268
9   2002  235235.596753            NaN -10.894485        NaN   56.662436
10  2003  256023.462375            NaN   8.837041        NaN   61.669719
11  2004  279141.288632  485115.195206   9.029573        NaN   67.238231
12  2005  304763.528550  528055.942503   9.178950   8.851660   73.189931
13  2006  330564.970472  570549.404221   8.466053   8.047152   79.079635
14  2007  359169.902946  621942.502646   8.653347   9.007651   86.202853
15  2008  383444.183250  647176.159741   6.758439   4.057233   89.700303
16  2009  386704.384733  608872.876413   0.850241  -5.918525   84.391368
17  2010  422130.052161  670523.679442   9.160917  10.125398   92.936331
18  2011  459571.104696  710781.597221   8.869554   6.003952   98.516183
19  2012  468301.016798  703485.989459   1.899578  -1.026420   97.504993
20  2013            NaN  720407.105303        NaN   2.405324   99.850303
21  2014            NaN  702306.045963        NaN  -2.512615   97.341449
22  2015            NaN  721487.146638        NaN   2.731160  100.000000
23  2016            NaN  706477.848598        NaN  -2.080328   97.919672
24  2017            NaN  726389.947763        NaN   2.818503  100.679541
25  2018            NaN  707755.489604        NaN  -2.565352   98.096757
26  2019            NaN  692977.449784        NaN  -2.088015   96.048482
27  2020            NaN  624336.405910        NaN  -9.905235   86.534654

In [3]:
"|BUILD PLOT|"

cds = ColumnDataSource(data)
#BUILD FIGURE
p = figure(title        = "EL HUB ECONÓMICO | PBI REAL (1994 - 2020)",
           y_axis_label = "PBI (tasa de crecimiento)",
           y_range      = (-15, 15),
           plot_height  = 400,
           plot_width   = 700)

p.toolbar_location = "right"
p.toolbar.autohide = True
p.add_tools(HoverTool(tooltips = [("Año", "@YEAR"), ("%PBI (1993)", "@1993"), ("%PBI (2004)", "@2004"), ("2005=100", "@Y_100")]))


#AXIS 1 (LEFT)
p.vbar(x=dodge('YEAR', -0.20, range=p.x_range), top='1993', color="red" , width=0.25, fill_alpha=0.50, legend_label="Base 1993", muted_alpha=0.2, source=cds)
p.vbar(x=dodge('YEAR',  0.20, range=p.x_range), top='2004', color="blue", width=0.25, fill_alpha=0.50, legend_label="Base 2004", muted_alpha=0.2, source=cds)

#AXIS 2 (RIGHT)
p.extra_y_ranges = {"y2": Range1d(start=0, end=120)}
p.add_layout(LinearAxis(y_range_name = "y2", axis_label = "2005 = 100"), 'right')
p.line  ('YEAR', 'Y_100', color="grey", y_range_name = "y2", source=cds, muted_alpha=0.2, legend_label="2015 = 100")
p.circle('YEAR', 'Y_100', color="grey", y_range_name = "y2", source=cds, muted_alpha=0.2, size=7)

#LEGEND
p.legend.location     = "top_left"
p.legend.orientation  = "horizontal"
p.legend.click_policy = "mute"
show(p)

In [21]:
"|EXPORT .PNG FILE|"

export_png(p, filename="pbi_real.png")

'C:\\Users\\ncach\\OneDrive\\My Documents\\Research\\GitHub Repositories\\el-hub-economico\\static\\Jupyter Notebooks\\pbi_real.png'

In [41]:
"|# CREATE HTML FILE|"

output_file(filename="pbi_real.html", title="PBI real")
save(p)

'C:\\Users\\ncach\\OneDrive\\My Documents\\Research\\GitHub Repositories\\el-hub-economico\\static\\Jupyter Notebooks\\pbi_real.html'

In [4]:
"|CREATE JSON FILE|"
import json
import bokeh.embed

from bokeh.embed import json_item

j = json.dumps(json_item(p, "pbi_real"))
with open("pbi_real.json", "w") as fp:
    json.dump(j, fp)